force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Logs__c/Project_Logs__c.object-meta.xml
<CustomObject>
    <label>10K Project Logs</label>
    <nameField>
        <label>Project Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>10K Project Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Logs__c/fields/Expert__c.field-meta.xml
<CustomField>
    <fullName>Expert__c</fullName>
    <label>Expert</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Logs__c/fields/Project_Member_id__c.field-meta.xml
<CustomField>
    <fullName>Project_Member_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Member id</label>
    <referenceTo>Project_Member__c</referenceTo>
    <relationshipName>Project_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0}</displayFormat>
        <label>Project Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Expert__c.field-meta.xml
<CustomField>
    <fullName>Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expert</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project_Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project_Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectLogsHandler.cls
public class ProjectLogsHandler {

    @future
    public static void updateProjectMemberIds(Set<Id> projectLogsIds) {
        List<Project_Logs__c> projectLogsToUpdate = [SELECT Id, Project__c, Expert__c, Project_Member_id__c FROM Project_Logs__c 
             WHERE Id IN :projectLogsIds AND Project_Member_id__c = null];

        Map<String, Id> mapPM = new Map<String, Id>();
        for (Project_Logs__c pml : projectLogsToUpdate) {
            String strC = pml.Project__c + pml.Expert__c;
            
            Project_Member__c pm = [SELECT Id FROM Project_Member__c WHERE Expert__c = :pml.Expert__c AND Project__c = :pml.Project__c LIMIT 1];
            if (pm != null) {
                mapPM.put(strC, pm.Id);
            }
        }

        List<Project_Logs__c> recordsToUpdate = new List<Project_Logs__c>();
        for (Project_Logs__c pml : projectLogsToUpdate) {
            String strC = pml.Project__c + pml.Expert__c;
            if (mapPM.containsKey(strC)) {
                pml.Project_Member_id__c = mapPM.get(strC);
                recordsToUpdate.add(pml);
            }
        }
        
        if (!recordsToUpdate.isEmpty()) {
            update recordsToUpdate;
        }
    }
}