force-app/main/default/objects/Account/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Harvest_logs__c/Harvest_logs__c.object-meta.xml
<CustomObject>
    <label>Harvest logs</label>
    <nameField>
        <label>Harvest logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Harvest_logs__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Harvest_logs__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Harvest_logs__c/fields/Project_Member_id__c.field-meta.xml
<CustomField>
    <fullName>Project_Member_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Member id</label>
    <referenceTo>Project_Member__c</referenceTo>
    <relationshipLabel>Harvest logs</relationshipLabel>
    <relationshipName>Harvest_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>Inv/23-24/-{000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Logs__c/Project_Logs__c.object-meta.xml
<CustomObject>
    <label>10K Project Logs</label>
    <nameField>
        <label>Project Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>10K Project Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Logs__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Logs__c/fields/Project_Member_id__c.field-meta.xml
<CustomField>
    <fullName>Project_Member_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Member id</label>
    <referenceTo>Project_Member__c</referenceTo>
    <relationshipName>Project_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0}</displayFormat>
        <label>Project Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project_Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project_role__c.field-meta.xml
<CustomField>
    <fullName>Project_role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Role</label>
    <referenceTo>Project_role__c</referenceTo>
    <relationshipLabel>Project_Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_role__c/Project_role__c.object-meta.xml
<CustomObject>
    <label>Project Role</label>
    <nameField>
        <label>Project role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceController.cls
public with sharing class InvoiceController {
    //public Id accountId { get; set; }
    //public Date startDate { get; set; }
    //public Date endDate { get; set; }
    //public String invoiceNumber { get; set; }
    //public String terms { get; set; }
    //public String gstin { get; set; }
    //public String invoiceTerms { get; set; }
    public Date invoiceDate { get; set; }
    public Decimal totalAmount { get; set; }
    public Id invoiceId { get; set; }
    public Invoice__c invoice { get; set; }
    public List<Invoice_Line_Item__c> invoiceLineItems { get; set; }
    
    public InvoiceController() {
        invoiceId = ApexPages.currentPage().getParameters().get('id');
        invoiceDate=date.today();
        System.debug('invoiceId'+invoiceId);
        if (invoiceId != null) {
            
            invoice = [
                SELECT Id, Attention__c, Start_Date__c, End_Date__c, Client__c, Invoice_Number__c, Terms__c, GSTIN__c, Date__c,
                (SELECT Id, Description__c, Hours__c, Hourly_Rate__c, Total_Cost__c
                 FROM Invoice_Line_Items__r)
                FROM Invoice__c
                WHERE Id = :invoiceId
            ];
            invoiceLineItems=invoice.Invoice_Line_Items__r;
            system.debug('@invoiceLineItems'+invoiceLineItems);
            totalAmount = 0;
            for (Invoice_Line_Item__c lineItem : invoiceLineItems) {
                totalAmount += lineItem.Total_Cost__c;}
            /*if (invoiceId == null) {
ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid invoice ID.'));
}*/
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid invoice ID.'));
        }
    }
    
    public class ProjectLogWrapper {
        // @AuraEnabled public Id Id { get; set; }
        @AuraEnabled public String Project { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public Decimal totalHours { get; set; }
        @AuraEnabled public Decimal HR { get; set; }
        
        public ProjectLogWrapper(AggregateResult aggregateResult) {
            this.Project = (String) aggregateResult.get('Project__c');
            this.name = (String) aggregateResult.get('name');
            this.totalHours = (Decimal) aggregateResult.get('totalHours');
            this.HR = (Decimal) aggregateResult.get('HR');
        }
    }
    
    @AuraEnabled
    public static List<ProjectLogWrapper> getProjectLogs(Date startDate, Date endDate, Id clientId) {
        startDate = Date.newInstance(startDate.year(), startDate.month(), startDate.day());
        endDate = Date.newInstance(endDate.year(), endDate.month(), endDate.day());
        
        
        List<ProjectLogWrapper> wrappedLogs = new List<ProjectLogWrapper>();
        if(clientId=='0015i00000yQM2EAAW'){
            
            
            List<AggregateResult> projectLogs = [
                SELECT Project__c, Project_Member_id__r.Project_role__r.name, SUM(Hours__c) totalHours,
                MAX(Project_Member_id__r.Hourly_Rate__c) HR
                FROM Project_Logs__c
                WHERE Date__c >= :startDate AND Date__c <= :endDate AND Project_Member_id__r.Client__c = :clientId
                GROUP BY Project__c, Project_Member_id__r.Project_role__r.name
            ];
            
            for (AggregateResult aggregateResult : projectLogs) {
                wrappedLogs.add(new ProjectLogWrapper(aggregateResult));
            }
        }else {
            List<AggregateResult> projectLogs = [
                SELECT Project__c, Project_Member_id__r.Project_role__r.name, SUM(Hours__c) totalHours,
                MAX(Project_Member_id__r.Hourly_Rate__c) HR
                FROM Harvest_logs__c
                WHERE Date__c >= :startDate AND Date__c <= :endDate AND Project_Member_id__r.Client__c = :clientId
                GROUP BY Project__c, Project_Member_id__r.Project_role__r.name
                
            ];
            for (AggregateResult aggregateResult : projectLogs) {
                wrappedLogs.add(new ProjectLogWrapper(aggregateResult));
            }
            
        }
        
        
        
        System.debug('Fetched Project Logs: ' + wrappedLogs);
        return wrappedLogs;
    }
    
    @AuraEnabled
    public static Map<String, String> getAccountDetails(Id accountId) {
        Map<String, String> accountDetails = new Map<String, String>();
        
        
        Account acc = [SELECT Attention__c, Terms__c, GSTIN__c FROM Account WHERE Id = :accountId LIMIT 1];
        
        // Populate the map with the retrieved values
        accountDetails.put('attention', acc.Attention__c);
        accountDetails.put('terms', acc.Terms__c);
        accountDetails.put('gstin', acc.GSTIN__c);
        
        return accountDetails;
    }
    @AuraEnabled
    public static Id createInvoice(String attention, Id accountId, Date startDate,String Terms, String GSTIN, Date endDate, List<Map<String, Object>> invoiceLineItems) {
        
        
        
        
        Invoice__c newInvoice = new Invoice__c();
        newInvoice.Attention__c = attention;
        newInvoice.Client__c = accountId; 
        newInvoice.Start_Date__c = startDate;
        newInvoice.End_Date__c = endDate;
        newInvoice.GSTIN__c = GSTIN;
        newInvoice.Terms__c = Terms;
        System.debug('Account.id'+accountId);
        insert newInvoice;
        System.debug('newInvoice.id'+newInvoice.id);
        
        
        
        List<Invoice_Line_Item__c> lineItemsToInsert = new List<Invoice_Line_Item__c>();
        for (Map<String, Object> lineItem : invoiceLineItems) {
            Invoice_Line_Item__c newItem = new Invoice_Line_Item__c();
            newItem.Description__c = (String) lineItem.get('Description');
            newItem.Hours__c = (Decimal) lineItem.get('Hours');
            newItem.Hourly_Rate__c = (Decimal) lineItem.get('Price');
            newItem.Total_Cost__c = (Decimal) lineItem.get('Cost');
            newItem.Invoice__c = (Id) lineItem.get('Invoice');
            
            newItem.Invoice__c = newInvoice.Id; 
            System.debug('newInvoice.Id---'+newInvoice.Id);
            
            lineItemsToInsert.add(newItem);
        }
        
        if (!lineItemsToInsert.isEmpty()) {
            insert lineItemsToInsert;
        }
        
        System.debug('invoiceLineItems: ' + invoiceLineItems);
        System.debug('accountId: ' + accountId);
        System.debug('startDate: ' + startDate);
        System.debug('endDate: ' + endDate);
        
        // Return the ID of the created Invoice
        System.debug('newInvoice.Id'+newInvoice.Id);
        Date currDate = Date.today();
        String formattedDate = currDate.format();//prints "2023-02-16"
        
        InvoiceController.createAttachment( accountId);
        System.debug('newInvoice.Id'+newInvoice.Id);
        return newInvoice.Id;
        
        
    }
    
    @AuraEnabled
    @Future(callout=true)
    public static void createAttachment(id accId){
        Account acc=[select Id,name,owner.name,owner.email from Account where id=:accId];
        
        Date currDate = Date.today();
        String formattedDate = currDate.format();//prints "2023-02-16"
        
        // Generate the invoice content and save it as a ContentVersion
        PageReference pageRef = Page.invoice; 
        pageRef.getParameters().put('accid', accId);
        Id accountId = accId;
        
        System.debug('Account Id for Content --'+accId);
        try {
            Blob pdfContent = pageRef.getContent();
            System.debug('  Blob pdfContent '+pageRef.getContent());
            
            
            ContentVersion cv = new ContentVersion();
            cv.Title = 'Invoice-' + formattedDate + '.pdf'; // Set the file name
            cv.PathOnClient = 'Invoice-' + formattedDate + '.pdf'; // Set the file path
            cv.VersionData = pdfContent; // Set the file content
            
            
            insert cv;
            
            System.debug('cv.id'+cv.id);
            
            // Create ContentDocumentLink to link the file to the Account record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1].ContentDocumentId;
            System.debug('ContentDocumentId--'+cdl.ContentDocumentId);
            cdl.LinkedEntityId = accountId;
            cdl.ShareType = 'V'; 
            cdl.Visibility = 'AllUsers'; 
            
            insert cdl;
            System.debug('cdl'+cdl);
            
            //////////////////////////
            
            
            /* // Prepare the email message
Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
email.setToAddresses(new List<String>{acc.Owner.Email});
email.setSubject('Invoice Created for Account ' + acc.Name);
email.setPlainTextBody('Hello ' + acc.Owner.Name + ',\n\n' +
'An invoice has been created for the account ' + acc.Name + '.\n\n' +
'Please find the attached invoice for your reference.\n\n' +
'Best regards,\nHelios Web Services');

// Attach the invoice PDF to the email
Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
attachment.setFileName(cv.Title);
attachment.setBody(pdfContent);
System.debug('pdfContent'+pdfContent);
email.setFileAttachments(new List<Messaging.EmailFileAttachment>{attachment});

// Send the email
System.debug('email'+email);
System.debug('To Addresses: ' + email.getToAddresses());
System.debug('Subject: ' + email.getSubject());
System.debug('Body: ' + email.getPlainTextBody());

Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});

*/
        } catch (Exception e) {
            System.debug('Error generating PDF or sending email: ' + e.getMessage());
        }        
    }
    
    
    
    
    
}